language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - "10"
script:
  - npm test
  - npm run travis-demo
  - ./bin/print-env.js --exists TRAVIS
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
